import { Inter } from 'next/font/google';
import './globals.css';
import { GoogleMapsEmbed, GoogleTagManager ,YouTubeEmbed} from '@next/third-parties/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <GoogleMapsEmbed
          apiKey='AIzaSyBmZUtDDF0hsC4ZM5bW32au8c2MZ5utJeA'
          height={200}
          width='100%'
          mode='place'
          q='Brooklyn+Bridge,New+York,NY'
        />
        <YouTubeEmbed videoid="ogfYd705cRs" height={400} params="controls=0" />
      </body>
      <GoogleTagManager gtmId='GTM-W6W5C3D' />
    </html>
  );
}
